name: Create and publish a Docker image

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  stage-1:
    strategy:
      matrix:
        image:
          - gcc-15
          - gcc-14
          - gcc-13
    permissions:
      id-token: write
      attestations: write
      contents: read
      packages: write
    uses: cynkra/docker-images/.github/workflows/publish.yml@main
    with:
      image: ${{ matrix.image }}
